# -*- coding: utf-8 -*-

# from plone import api
from popolo.contenttypes import _
from plone.dexterity.interfaces import IDexterityContent
from zope.globalrequest import getRequest
from zope.interface import implementer
from zope.schema.interfaces import IVocabularyFactory
from zope.schema.vocabulary import SimpleTerm
from zope.schema.vocabulary import SimpleVocabulary


class VocabItem(object):
    def __init__(self, token, value):
        self.token = token
        self.value = value


@implementer(IVocabularyFactory)
class GeonameFeaturecodesVocab(object):
    """
    """

    def __call__(self, context):
        # Just an example list of content for our vocabulary,
        # this can be any static or dynamic data, a catalog result for example.
        geoname_featurecodes = SimpleVocabulary(
            [
                SimpleTerm(value=_(u'A.ADM1'), title=_(u'first-order administrative division')),
                SimpleTerm(value=_(u'A.ADM1H'), title=_(u'historical first-order administrative division')),
                SimpleTerm(value=_(u'A.ADM2'), title=_(u'second-order administrative division')),
                SimpleTerm(value=_(u'A.ADM2H'), title=_(u'historical second-order administrative division')),
                SimpleTerm(value=_(u'A.ADM3'), title=_(u'third-order administrative division')),
                SimpleTerm(value=_(u'A.ADM3H'), title=_(u'historical third-order administrative division')),
                SimpleTerm(value=_(u'A.ADM4'), title=_(u'fourth-order administrative division')),
                SimpleTerm(value=_(u'A.ADM4H'), title=_(u'historical fourth-order administrative division')),
                SimpleTerm(value=_(u'A.ADM5'), title=_(u'fifth-order administrative division')),
                SimpleTerm(value=_(u'A.ADM5H'), title=_(u'historical fifth-order administrative division')),
                SimpleTerm(value=_(u'A.ADMD'), title=_(u'administrative division')),
                SimpleTerm(value=_(u'A.ADMDH'), title=_(u'historical administrative division')),
                SimpleTerm(value=_(u'A.LTER'), title=_(u'leased area')),
                SimpleTerm(value=_(u'A.PCL'), title=_(u'political entity')),
                SimpleTerm(value=_(u'A.PCLD'), title=_(u'dependent political entity')),
                SimpleTerm(value=_(u'A.PCLF'), title=_(u'freely associated state')),
                SimpleTerm(value=_(u'A.PCLH'), title=_(u'historical political entity')),
                SimpleTerm(value=_(u'A.PCLI'), title=_(u'independent political entity')),
                SimpleTerm(value=_(u'A.PCLIX'), title=_(u'section of independent political entity')),
                SimpleTerm(value=_(u'A.PCLS'), title=_(u'semi-independent political entity')),
                SimpleTerm(value=_(u'A.PRSH'), title=_(u'parish')),
                SimpleTerm(value=_(u'A.TERR'), title=_(u'territory')),
                SimpleTerm(value=_(u'A.ZN'), title=_(u'zone')),
                SimpleTerm(value=_(u'A.ZNB'), title=_(u'buffer zone')),
                SimpleTerm(value=_(u'H.AIRS'), title=_(u'seaplane landing area')),
                SimpleTerm(value=_(u'H.ANCH'), title=_(u'anchorage')),
                SimpleTerm(value=_(u'H.BAY'), title=_(u'bay')),
                SimpleTerm(value=_(u'H.BAYS'), title=_(u'bays')),
                SimpleTerm(value=_(u'H.BGHT'), title=_(u'bight(s)')),
                SimpleTerm(value=_(u'H.BNK'), title=_(u'bank(s)')),
                SimpleTerm(value=_(u'H.BNKR'), title=_(u'stream bank')),
                SimpleTerm(value=_(u'H.BNKX'), title=_(u'section of bank')),
                SimpleTerm(value=_(u'H.BOG'), title=_(u'bog(s)')),
                SimpleTerm(value=_(u'H.CAPG'), title=_(u'icecap')),
                SimpleTerm(value=_(u'H.CHN'), title=_(u'channel')),
                SimpleTerm(value=_(u'H.CHNL'), title=_(u'lake channel(s)')),
                SimpleTerm(value=_(u'H.CHNM'), title=_(u'marine channel')),
                SimpleTerm(value=_(u'H.CHNN'), title=_(u'navigation channel')),
                SimpleTerm(value=_(u'H.CNFL'), title=_(u'confluence')),
                SimpleTerm(value=_(u'H.CNL'), title=_(u'canal')),
                SimpleTerm(value=_(u'H.CNLA'), title=_(u'aqueduct')),
                SimpleTerm(value=_(u'H.CNLB'), title=_(u'canal bend')),
                SimpleTerm(value=_(u'H.CNLD'), title=_(u'drainage canal')),
                SimpleTerm(value=_(u'H.CNLI'), title=_(u'irrigation canal')),
                SimpleTerm(value=_(u'H.CNLN'), title=_(u'navigation canal(s)')),
                SimpleTerm(value=_(u'H.CNLQ'), title=_(u'abandoned canal')),
                SimpleTerm(value=_(u'H.CNLSB'), title=_(u'underground irrigation canal(s)')),
                SimpleTerm(value=_(u'H.CNLX'), title=_(u'section of canal')),
                SimpleTerm(value=_(u'H.COVE'), title=_(u'cove(s)')),
                SimpleTerm(value=_(u'H.CRKT'), title=_(u'tidal creek(s)')),
                SimpleTerm(value=_(u'H.CRNT'), title=_(u'current')),
                SimpleTerm(value=_(u'H.CUTF'), title=_(u'cutoff')),
                SimpleTerm(value=_(u'H.DCK'), title=_(u'dock(s)')),
                SimpleTerm(value=_(u'H.DCKB'), title=_(u'docking basin')),
                SimpleTerm(value=_(u'H.DOMG'), title=_(u'icecap dome')),
                SimpleTerm(value=_(u'H.DPRG'), title=_(u'icecap depression')),
                SimpleTerm(value=_(u'H.DTCH'), title=_(u'ditch')),
                SimpleTerm(value=_(u'H.DTCHD'), title=_(u'drainage ditch')),
                SimpleTerm(value=_(u'H.DTCHI'), title=_(u'irrigation ditch')),
                SimpleTerm(value=_(u'H.DTCHM'), title=_(u'ditch mouth(s)')),
                SimpleTerm(value=_(u'H.ESTY'), title=_(u'estuary')),
                SimpleTerm(value=_(u'H.FISH'), title=_(u'fishing area')),
                SimpleTerm(value=_(u'H.FJD'), title=_(u'fjord')),
                SimpleTerm(value=_(u'H.FJDS'), title=_(u'fjords')),
                SimpleTerm(value=_(u'H.FLLS'), title=_(u'waterfall(s)')),
                SimpleTerm(value=_(u'H.FLLSX'), title=_(u'section of waterfall(s)')),
                SimpleTerm(value=_(u'H.FLTM'), title=_(u'mud flat(s)')),
                SimpleTerm(value=_(u'H.FLTT'), title=_(u'tidal flat(s)')),
                SimpleTerm(value=_(u'H.GLCR'), title=_(u'glacier(s)')),
                SimpleTerm(value=_(u'H.GULF'), title=_(u'gulf')),
                SimpleTerm(value=_(u'H.GYSR'), title=_(u'geyser')),
                SimpleTerm(value=_(u'H.HBR'), title=_(u'harbor(s)')),
                SimpleTerm(value=_(u'H.HBRX'), title=_(u'section of harbor')),
                SimpleTerm(value=_(u'H.INLT'), title=_(u'inlet')),
                SimpleTerm(value=_(u'H.INLTQ'), title=_(u'former inlet')),
                SimpleTerm(value=_(u'H.LBED'), title=_(u'lake bed(s)')),
                SimpleTerm(value=_(u'H.LGN'), title=_(u'lagoon')),
                SimpleTerm(value=_(u'H.LGNS'), title=_(u'lagoons')),
                SimpleTerm(value=_(u'H.LGNX'), title=_(u'section of lagoon')),
                SimpleTerm(value=_(u'H.LK'), title=_(u'lake')),
                SimpleTerm(value=_(u'H.LKC'), title=_(u'crater lake')),
                SimpleTerm(value=_(u'H.LKI'), title=_(u'intermittent lake')),
                SimpleTerm(value=_(u'H.LKN'), title=_(u'salt lake')),
                SimpleTerm(value=_(u'H.LKNI'), title=_(u'intermittent salt lake')),
                SimpleTerm(value=_(u'H.LKO'), title=_(u'oxbow lake')),
                SimpleTerm(value=_(u'H.LKOI'), title=_(u'intermittent oxbow lake')),
                SimpleTerm(value=_(u'H.LKS'), title=_(u'lakes')),
                SimpleTerm(value=_(u'H.LKSB'), title=_(u'underground lake')),
                SimpleTerm(value=_(u'H.LKSC'), title=_(u'crater lakes')),
                SimpleTerm(value=_(u'H.LKSI'), title=_(u'intermittent lakes')),
                SimpleTerm(value=_(u'H.LKSN'), title=_(u'salt lakes')),
                SimpleTerm(value=_(u'H.LKSNI'), title=_(u'intermittent salt lakes')),
                SimpleTerm(value=_(u'H.LKX'), title=_(u'section of lake')),
                SimpleTerm(value=_(u'H.MFGN'), title=_(u'salt evaporation ponds')),
                SimpleTerm(value=_(u'H.MGV'), title=_(u'mangrove swamp')),
                SimpleTerm(value=_(u'H.MOOR'), title=_(u'moor(s)')),
                SimpleTerm(value=_(u'H.MRSH'), title=_(u'marsh(es)')),
                SimpleTerm(value=_(u'H.MRSHN'), title=_(u'salt marsh')),
                SimpleTerm(value=_(u'H.NRWS'), title=_(u'narrows')),
                SimpleTerm(value=_(u'H.OCN'), title=_(u'ocean')),
                SimpleTerm(value=_(u'H.OVF'), title=_(u'overfalls')),
                SimpleTerm(value=_(u'H.PND'), title=_(u'pond')),
                SimpleTerm(value=_(u'H.PNDI'), title=_(u'intermittent pond')),
                SimpleTerm(value=_(u'H.PNDN'), title=_(u'salt pond')),
                SimpleTerm(value=_(u'H.PNDNI'), title=_(u'intermittent salt pond(s)')),
                SimpleTerm(value=_(u'H.PNDS'), title=_(u'ponds')),
                SimpleTerm(value=_(u'H.PNDSF'), title=_(u'fishponds')),
                SimpleTerm(value=_(u'H.PNDSI'), title=_(u'intermittent ponds')),
                SimpleTerm(value=_(u'H.PNDSN'), title=_(u'salt ponds')),
                SimpleTerm(value=_(u'H.POOL'), title=_(u'pool(s)')),
                SimpleTerm(value=_(u'H.POOLI'), title=_(u'intermittent pool')),
                SimpleTerm(value=_(u'H.RCH'), title=_(u'reach')),
                SimpleTerm(value=_(u'H.RDGG'), title=_(u'icecap ridge')),
                SimpleTerm(value=_(u'H.RDST'), title=_(u'roadstead')),
                SimpleTerm(value=_(u'H.RF'), title=_(u'reef(s)')),
                SimpleTerm(value=_(u'H.RFC'), title=_(u'coral reef(s)')),
                SimpleTerm(value=_(u'H.RFX'), title=_(u'section of reef')),
                SimpleTerm(value=_(u'H.RPDS'), title=_(u'rapids')),
                SimpleTerm(value=_(u'H.RSV'), title=_(u'reservoir(s)')),
                SimpleTerm(value=_(u'H.RSVI'), title=_(u'intermittent reservoir')),
                SimpleTerm(value=_(u'H.RSVT'), title=_(u'water tank')),
                SimpleTerm(value=_(u'H.RVN'), title=_(u'ravine(s)')),
                SimpleTerm(value=_(u'H.SBKH'), title=_(u'sabkha(s)')),
                SimpleTerm(value=_(u'H.SD'), title=_(u'sound')),
                SimpleTerm(value=_(u'H.SEA'), title=_(u'sea')),
                SimpleTerm(value=_(u'H.SHOL'), title=_(u'shoal(s)')),
                SimpleTerm(value=_(u'H.SILL'), title=_(u'sill')),
                SimpleTerm(value=_(u'H.SPNG'), title=_(u'spring(s)')),
                SimpleTerm(value=_(u'H.SPNS'), title=_(u'sulphur spring(s)')),
                SimpleTerm(value=_(u'H.SPNT'), title=_(u'hot spring(s)')),
                SimpleTerm(value=_(u'H.STM'), title=_(u'stream')),
                SimpleTerm(value=_(u'H.STMA'), title=_(u'anabranch')),
                SimpleTerm(value=_(u'H.STMB'), title=_(u'stream bend')),
                SimpleTerm(value=_(u'H.STMC'), title=_(u'canalized stream')),
                SimpleTerm(value=_(u'H.STMD'), title=_(u'distributary(-ies)')),
                SimpleTerm(value=_(u'H.STMH'), title=_(u'headwaters')),
                SimpleTerm(value=_(u'H.STMI'), title=_(u'intermittent stream')),
                SimpleTerm(value=_(u'H.STMIX'), title=_(u'section of intermittent stream')),
                SimpleTerm(value=_(u'H.STMM'), title=_(u'stream mouth(s)')),
                SimpleTerm(value=_(u'H.STMQ'), title=_(u'abandoned watercourse')),
                SimpleTerm(value=_(u'H.STMS'), title=_(u'streams')),
                SimpleTerm(value=_(u'H.STMSB'), title=_(u'lost river')),
                SimpleTerm(value=_(u'H.STMX'), title=_(u'section of stream')),
                SimpleTerm(value=_(u'H.STRT'), title=_(u'strait')),
                SimpleTerm(value=_(u'H.SWMP'), title=_(u'swamp')),
                SimpleTerm(value=_(u'H.SYSI'), title=_(u'irrigation system')),
                SimpleTerm(value=_(u'H.TNLC'), title=_(u'canal tunnel')),
                SimpleTerm(value=_(u'H.WAD'), title=_(u'wadi')),
                SimpleTerm(value=_(u'H.WADB'), title=_(u'wadi bend')),
                SimpleTerm(value=_(u'H.WADJ'), title=_(u'wadi junction')),
                SimpleTerm(value=_(u'H.WADM'), title=_(u'wadi mouth')),
                SimpleTerm(value=_(u'H.WADS'), title=_(u'wadies')),
                SimpleTerm(value=_(u'H.WADX'), title=_(u'section of wadi')),
                SimpleTerm(value=_(u'H.WHRL'), title=_(u'whirlpool')),
                SimpleTerm(value=_(u'H.WLL'), title=_(u'well')),
                SimpleTerm(value=_(u'H.WLLQ'), title=_(u'abandoned well')),
                SimpleTerm(value=_(u'H.WLLS'), title=_(u'wells')),
                SimpleTerm(value=_(u'H.WTLD'), title=_(u'wetland')),
                SimpleTerm(value=_(u'H.WTLDI'), title=_(u'intermittent wetland')),
                SimpleTerm(value=_(u'H.WTRC'), title=_(u'watercourse')),
                SimpleTerm(value=_(u'H.WTRH'), title=_(u'waterhole(s)')),
                SimpleTerm(value=_(u'L.AGRC'), title=_(u'agricultural colony')),
                SimpleTerm(value=_(u'L.AMUS'), title=_(u'amusement park')),
                SimpleTerm(value=_(u'L.AREA'), title=_(u'area')),
                SimpleTerm(value=_(u'L.BSND'), title=_(u'drainage basin')),
                SimpleTerm(value=_(u'L.BSNP'), title=_(u'petroleum basin')),
                SimpleTerm(value=_(u'L.BTL'), title=_(u'battlefield')),
                SimpleTerm(value=_(u'L.CLG'), title=_(u'clearing')),
                SimpleTerm(value=_(u'L.CMN'), title=_(u'common')),
                SimpleTerm(value=_(u'L.CNS'), title=_(u'concession area')),
                SimpleTerm(value=_(u'L.COLF'), title=_(u'coalfield')),
                SimpleTerm(value=_(u'L.CONT'), title=_(u'continent')),
                SimpleTerm(value=_(u'L.CST'), title=_(u'coast')),
                SimpleTerm(value=_(u'L.CTRB'), title=_(u'business center')),
                SimpleTerm(value=_(u'L.DEVH'), title=_(u'housing development')),
                SimpleTerm(value=_(u'L.FLD'), title=_(u'field(s)')),
                SimpleTerm(value=_(u'L.FLDI'), title=_(u'irrigated field(s)')),
                SimpleTerm(value=_(u'L.GASF'), title=_(u'gasfield')),
                SimpleTerm(value=_(u'L.GRAZ'), title=_(u'grazing area')),
                SimpleTerm(value=_(u'L.GVL'), title=_(u'gravel area')),
                SimpleTerm(value=_(u'L.INDS'), title=_(u'industrial area')),
                SimpleTerm(value=_(u'L.LAND'), title=_(u'arctic land')),
                SimpleTerm(value=_(u'L.LCTY'), title=_(u'locality')),
                SimpleTerm(value=_(u'L.MILB'), title=_(u'military base')),
                SimpleTerm(value=_(u'L.MNA'), title=_(u'mining area')),
                SimpleTerm(value=_(u'L.MVA'), title=_(u'maneuver area')),
                SimpleTerm(value=_(u'L.NVB'), title=_(u'naval base')),
                SimpleTerm(value=_(u'L.OAS'), title=_(u'oasis(-es)')),
                SimpleTerm(value=_(u'L.OILF'), title=_(u'oilfield')),
                SimpleTerm(value=_(u'L.PEAT'), title=_(u'peat cutting area')),
                SimpleTerm(value=_(u'L.PRK'), title=_(u'park')),
                SimpleTerm(value=_(u'L.PRT'), title=_(u'port')),
                SimpleTerm(value=_(u'L.QCKS'), title=_(u'quicksand')),
                SimpleTerm(value=_(u'L.RES'), title=_(u'reserve')),
                SimpleTerm(value=_(u'L.RESA'), title=_(u'agricultural reserve')),
                SimpleTerm(value=_(u'L.RESF'), title=_(u'forest reserve')),
                SimpleTerm(value=_(u'L.RESH'), title=_(u'hunting reserve')),
                SimpleTerm(value=_(u'L.RESN'), title=_(u'nature reserve')),
                SimpleTerm(value=_(u'L.RESP'), title=_(u'palm tree reserve')),
                SimpleTerm(value=_(u'L.RESV'), title=_(u'reservation')),
                SimpleTerm(value=_(u'L.RESW'), title=_(u'wildlife reserve')),
                SimpleTerm(value=_(u'L.RGN'), title=_(u'region')),
                SimpleTerm(value=_(u'L.RGNE'), title=_(u'economic region')),
                SimpleTerm(value=_(u'L.RGNH'), title=_(u'historical region')),
                SimpleTerm(value=_(u'L.RGNL'), title=_(u'lake region')),
                SimpleTerm(value=_(u'L.RNGA'), title=_(u'artillery range')),
                SimpleTerm(value=_(u'L.SALT'), title=_(u'salt area')),
                SimpleTerm(value=_(u'L.SNOW'), title=_(u'snowfield')),
                SimpleTerm(value=_(u'L.TRB'), title=_(u'tribal area')),
                SimpleTerm(value=_(u'P.PPL'), title=_(u'populated place')),
                SimpleTerm(value=_(u'P.PPLA'), title=_(u'seat of a first-order administrative division')),
                SimpleTerm(value=_(u'P.PPLA2'), title=_(u'seat of a second-order administrative division')),
                SimpleTerm(value=_(u'P.PPLA3'), title=_(u'seat of a third-order administrative division')),
                SimpleTerm(value=_(u'P.PPLA4'), title=_(u'seat of a fourth-order administrative division')),
                SimpleTerm(value=_(u'P.PPLA5'), title=_(u'seat of a fifth-order administrative division')),
                SimpleTerm(value=_(u'P.PPLC'), title=_(u'capital of a political entity')),
                SimpleTerm(value=_(u'P.PPLCH'), title=_(u'historical capital of a political entity')),
                SimpleTerm(value=_(u'P.PPLF'), title=_(u'farm village')),
                SimpleTerm(value=_(u'P.PPLG'), title=_(u'seat of government of a political entity')),
                SimpleTerm(value=_(u'P.PPLH'), title=_(u'historical populated place')),
                SimpleTerm(value=_(u'P.PPLL'), title=_(u'populated locality')),
                SimpleTerm(value=_(u'P.PPLQ'), title=_(u'abandoned populated place')),
                SimpleTerm(value=_(u'P.PPLR'), title=_(u'religious populated place')),
                SimpleTerm(value=_(u'P.PPLS'), title=_(u'populated places')),
                SimpleTerm(value=_(u'P.PPLW'), title=_(u'destroyed populated place')),
                SimpleTerm(value=_(u'P.PPLX'), title=_(u'section of populated place')),
                SimpleTerm(value=_(u'P.STLMT'), title=_(u'israeli settlement')),
                SimpleTerm(value=_(u'R.CSWY'), title=_(u'causeway')),
                SimpleTerm(value=_(u'R.OILP'), title=_(u'oil pipeline')),
                SimpleTerm(value=_(u'R.PRMN'), title=_(u'promenade')),
                SimpleTerm(value=_(u'R.PTGE'), title=_(u'portage')),
                SimpleTerm(value=_(u'R.RD'), title=_(u'road')),
                SimpleTerm(value=_(u'R.RDA'), title=_(u'ancient road')),
                SimpleTerm(value=_(u'R.RDB'), title=_(u'road bend')),
                SimpleTerm(value=_(u'R.RDCUT'), title=_(u'road cut')),
                SimpleTerm(value=_(u'R.RDJCT'), title=_(u'road junction')),
                SimpleTerm(value=_(u'R.RJCT'), title=_(u'railroad junction')),
                SimpleTerm(value=_(u'R.RR'), title=_(u'railroad')),
                SimpleTerm(value=_(u'R.RRQ'), title=_(u'abandoned railroad')),
                SimpleTerm(value=_(u'R.RTE'), title=_(u'caravan route')),
                SimpleTerm(value=_(u'R.RYD'), title=_(u'railroad yard')),
                SimpleTerm(value=_(u'R.ST'), title=_(u'street')),
                SimpleTerm(value=_(u'R.STKR'), title=_(u'stock route')),
                SimpleTerm(value=_(u'R.TNL'), title=_(u'tunnel')),
                SimpleTerm(value=_(u'R.TNLN'), title=_(u'natural tunnel')),
                SimpleTerm(value=_(u'R.TNLRD'), title=_(u'road tunnel')),
                SimpleTerm(value=_(u'R.TNLRR'), title=_(u'railroad tunnel')),
                SimpleTerm(value=_(u'R.TNLS'), title=_(u'tunnels')),
                SimpleTerm(value=_(u'R.TRL'), title=_(u'trail')),
                SimpleTerm(value=_(u'S.ADMF'), title=_(u'administrative facility')),
                SimpleTerm(value=_(u'S.AGRF'), title=_(u'agricultural facility')),
                SimpleTerm(value=_(u'S.AIRB'), title=_(u'airbase')),
                SimpleTerm(value=_(u'S.AIRF'), title=_(u'airfield')),
                SimpleTerm(value=_(u'S.AIRH'), title=_(u'heliport')),
                SimpleTerm(value=_(u'S.AIRP'), title=_(u'airport')),
                SimpleTerm(value=_(u'S.AIRQ'), title=_(u'abandoned airfield')),
                SimpleTerm(value=_(u'S.AIRT'), title=_(u'terminal')),
                SimpleTerm(value=_(u'S.AMTH'), title=_(u'amphitheater')),
                SimpleTerm(value=_(u'S.ANS'), title=_(u'archaeological/prehistoric site')),
                SimpleTerm(value=_(u'S.AQC'), title=_(u'aquaculture facility')),
                SimpleTerm(value=_(u'S.ARCH'), title=_(u'arch')),
                SimpleTerm(value=_(u'S.ARCHV'), title=_(u'archive')),
                SimpleTerm(value=_(u'S.ART'), title=_(u'piece of art')),
                SimpleTerm(value=_(u'S.ASTR'), title=_(u'astronomical station')),
                SimpleTerm(value=_(u'S.ASYL'), title=_(u'asylum')),
                SimpleTerm(value=_(u'S.ATHF'), title=_(u'athletic field')),
                SimpleTerm(value=_(u'S.ATM'), title=_(u'automatic teller machine')),
                SimpleTerm(value=_(u'S.BANK'), title=_(u'bank')),
                SimpleTerm(value=_(u'S.BCN'), title=_(u'beacon')),
                SimpleTerm(value=_(u'S.BDG'), title=_(u'bridge')),
                SimpleTerm(value=_(u'S.BDGQ'), title=_(u'ruined bridge')),
                SimpleTerm(value=_(u'S.BLDA'), title=_(u'apartment building')),
                SimpleTerm(value=_(u'S.BLDG'), title=_(u'building(s)')),
                SimpleTerm(value=_(u'S.BLDO'), title=_(u'office building')),
                SimpleTerm(value=_(u'S.BP'), title=_(u'boundary marker')),
                SimpleTerm(value=_(u'S.BRKS'), title=_(u'barracks')),
                SimpleTerm(value=_(u'S.BRKW'), title=_(u'breakwater')),
                SimpleTerm(value=_(u'S.BSTN'), title=_(u'baling station')),
                SimpleTerm(value=_(u'S.BTYD'), title=_(u'boatyard')),
                SimpleTerm(value=_(u'S.BUR'), title=_(u'burial cave(s)')),
                SimpleTerm(value=_(u'S.BUSTN'), title=_(u'bus station')),
                SimpleTerm(value=_(u'S.BUSTP'), title=_(u'bus stop')),
                SimpleTerm(value=_(u'S.CARN'), title=_(u'cairn')),
                SimpleTerm(value=_(u'S.CAVE'), title=_(u'cave(s)')),
                SimpleTerm(value=_(u'S.CH'), title=_(u'church')),
                SimpleTerm(value=_(u'S.CMP'), title=_(u'camp(s)')),
                SimpleTerm(value=_(u'S.CMPL'), title=_(u'logging camp')),
                SimpleTerm(value=_(u'S.CMPLA'), title=_(u'labor camp')),
                SimpleTerm(value=_(u'S.CMPMN'), title=_(u'mining camp')),
                SimpleTerm(value=_(u'S.CMPO'), title=_(u'oil camp')),
                SimpleTerm(value=_(u'S.CMPQ'), title=_(u'abandoned camp')),
                SimpleTerm(value=_(u'S.CMPRF'), title=_(u'refugee camp')),
                SimpleTerm(value=_(u'S.CMTY'), title=_(u'cemetery')),
                SimpleTerm(value=_(u'S.COMC'), title=_(u'communication center')),
                SimpleTerm(value=_(u'S.CRRL'), title=_(u'corral(s)')),
                SimpleTerm(value=_(u'S.CSNO'), title=_(u'casino')),
                SimpleTerm(value=_(u'S.CSTL'), title=_(u'castle')),
                SimpleTerm(value=_(u'S.CSTM'), title=_(u'customs house')),
                SimpleTerm(value=_(u'S.CTHSE'), title=_(u'courthouse')),
                SimpleTerm(value=_(u'S.CTRA'), title=_(u'atomic center')),
                SimpleTerm(value=_(u'S.CTRCM'), title=_(u'community center')),
                SimpleTerm(value=_(u'S.CTRF'), title=_(u'facility center')),
                SimpleTerm(value=_(u'S.CTRM'), title=_(u'medical center')),
                SimpleTerm(value=_(u'S.CTRR'), title=_(u'religious center')),
                SimpleTerm(value=_(u'S.CTRS'), title=_(u'space center')),
                SimpleTerm(value=_(u'S.CVNT'), title=_(u'convent')),
                SimpleTerm(value=_(u'S.DAM'), title=_(u'dam')),
                SimpleTerm(value=_(u'S.DAMQ'), title=_(u'ruined dam')),
                SimpleTerm(value=_(u'S.DAMSB'), title=_(u'sub-surface dam')),
                SimpleTerm(value=_(u'S.DARY'), title=_(u'dairy')),
                SimpleTerm(value=_(u'S.DCKD'), title=_(u'dry dock')),
                SimpleTerm(value=_(u'S.DCKY'), title=_(u'dockyard')),
                SimpleTerm(value=_(u'S.DIKE'), title=_(u'dike')),
                SimpleTerm(value=_(u'S.DIP'), title=_(u'diplomatic facility')),
                SimpleTerm(value=_(u'S.DPOF'), title=_(u'fuel depot')),
                SimpleTerm(value=_(u'S.EST'), title=_(u'estate(s)')),
                SimpleTerm(value=_(u'S.ESTO'), title=_(u'oil palm plantation')),
                SimpleTerm(value=_(u'S.ESTR'), title=_(u'rubber plantation')),
                SimpleTerm(value=_(u'S.ESTSG'), title=_(u'sugar plantation')),
                SimpleTerm(value=_(u'S.ESTT'), title=_(u'tea plantation')),
                SimpleTerm(value=_(u'S.ESTX'), title=_(u'section of estate')),
                SimpleTerm(value=_(u'S.FCL'), title=_(u'facility')),
                SimpleTerm(value=_(u'S.FNDY'), title=_(u'foundry')),
                SimpleTerm(value=_(u'S.FRM'), title=_(u'farm')),
                SimpleTerm(value=_(u'S.FRMQ'), title=_(u'abandoned farm')),
                SimpleTerm(value=_(u'S.FRMS'), title=_(u'farms')),
                SimpleTerm(value=_(u'S.FRMT'), title=_(u'farmstead')),
                SimpleTerm(value=_(u'S.FT'), title=_(u'fort')),
                SimpleTerm(value=_(u'S.FY'), title=_(u'ferry')),
                SimpleTerm(value=_(u'S.FYT'), title=_(u'ferry terminal')),
                SimpleTerm(value=_(u'S.GATE'), title=_(u'gate')),
                SimpleTerm(value=_(u'S.GDN'), title=_(u'garden(s)')),
                SimpleTerm(value=_(u'S.GHAT'), title=_(u'ghat')),
                SimpleTerm(value=_(u'S.GHSE'), title=_(u'guest house')),
                SimpleTerm(value=_(u'S.GOSP'), title=_(u'gas-oil separator plant')),
                SimpleTerm(value=_(u'S.GOVL'), title=_(u'local government office')),
                SimpleTerm(value=_(u'S.GRVE'), title=_(u'grave')),
                SimpleTerm(value=_(u'S.HERM'), title=_(u'hermitage')),
                SimpleTerm(value=_(u'S.HLT'), title=_(u'halting place')),
                SimpleTerm(value=_(u'S.HMSD'), title=_(u'homestead')),
                SimpleTerm(value=_(u'S.HSE'), title=_(u'house(s)')),
                SimpleTerm(value=_(u'S.HSEC'), title=_(u'country house')),
                SimpleTerm(value=_(u'S.HSP'), title=_(u'hospital')),
                SimpleTerm(value=_(u'S.HSPC'), title=_(u'clinic')),
                SimpleTerm(value=_(u'S.HSPD'), title=_(u'dispensary')),
                SimpleTerm(value=_(u'S.HSPL'), title=_(u'leprosarium')),
                SimpleTerm(value=_(u'S.HSTS'), title=_(u'historical site')),
                SimpleTerm(value=_(u'S.HTL'), title=_(u'hotel')),
                SimpleTerm(value=_(u'S.HUT'), title=_(u'hut')),
                SimpleTerm(value=_(u'S.HUTS'), title=_(u'huts')),
                SimpleTerm(value=_(u'S.INSM'), title=_(u'military installation')),
                SimpleTerm(value=_(u'S.ITTR'), title=_(u'research institute')),
                SimpleTerm(value=_(u'S.JTY'), title=_(u'jetty')),
                SimpleTerm(value=_(u'S.LDNG'), title=_(u'landing')),
                SimpleTerm(value=_(u'S.LEPC'), title=_(u'leper colony')),
                SimpleTerm(value=_(u'S.LIBR'), title=_(u'library')),
                SimpleTerm(value=_(u'S.LNDF'), title=_(u'landfill')),
                SimpleTerm(value=_(u'S.LOCK'), title=_(u'lock(s)')),
                SimpleTerm(value=_(u'S.LTHSE'), title=_(u'lighthouse')),
                SimpleTerm(value=_(u'S.MALL'), title=_(u'mall')),
                SimpleTerm(value=_(u'S.MAR'), title=_(u'marina')),
                SimpleTerm(value=_(u'S.MFG'), title=_(u'factory')),
                SimpleTerm(value=_(u'S.MFGB'), title=_(u'brewery')),
                SimpleTerm(value=_(u'S.MFGC'), title=_(u'cannery')),
                SimpleTerm(value=_(u'S.MFGCU'), title=_(u'copper works')),
                SimpleTerm(value=_(u'S.MFGLM'), title=_(u'limekiln')),
                SimpleTerm(value=_(u'S.MFGM'), title=_(u'munitions plant')),
                SimpleTerm(value=_(u'S.MFGPH'), title=_(u'phosphate works')),
                SimpleTerm(value=_(u'S.MFGQ'), title=_(u'abandoned factory')),
                SimpleTerm(value=_(u'S.MFGSG'), title=_(u'sugar refinery')),
                SimpleTerm(value=_(u'S.MKT'), title=_(u'market')),
                SimpleTerm(value=_(u'S.ML'), title=_(u'mill(s)')),
                SimpleTerm(value=_(u'S.MLM'), title=_(u'ore treatment plant')),
                SimpleTerm(value=_(u'S.MLO'), title=_(u'olive oil mill')),
                SimpleTerm(value=_(u'S.MLSG'), title=_(u'sugar mill')),
                SimpleTerm(value=_(u'S.MLSGQ'), title=_(u'former sugar mill')),
                SimpleTerm(value=_(u'S.MLSW'), title=_(u'sawmill')),
                SimpleTerm(value=_(u'S.MLWND'), title=_(u'windmill')),
                SimpleTerm(value=_(u'S.MLWTR'), title=_(u'water mill')),
                SimpleTerm(value=_(u'S.MN'), title=_(u'mine(s)')),
                SimpleTerm(value=_(u'S.MNAU'), title=_(u'gold mine(s)')),
                SimpleTerm(value=_(u'S.MNC'), title=_(u'coal mine(s)')),
                SimpleTerm(value=_(u'S.MNCR'), title=_(u'chrome mine(s)')),
                SimpleTerm(value=_(u'S.MNCU'), title=_(u'copper mine(s)')),
                SimpleTerm(value=_(u'S.MNFE'), title=_(u'iron mine(s)')),
                SimpleTerm(value=_(u'S.MNMT'), title=_(u'monument')),
                SimpleTerm(value=_(u'S.MNN'), title=_(u'salt mine(s)')),
                SimpleTerm(value=_(u'S.MNQ'), title=_(u'abandoned mine')),
                SimpleTerm(value=_(u'S.MNQR'), title=_(u'quarry(-ies)')),
                SimpleTerm(value=_(u'S.MOLE'), title=_(u'mole')),
                SimpleTerm(value=_(u'S.MSQE'), title=_(u'mosque')),
                SimpleTerm(value=_(u'S.MSSN'), title=_(u'mission')),
                SimpleTerm(value=_(u'S.MSSNQ'), title=_(u'abandoned mission')),
                SimpleTerm(value=_(u'S.MSTY'), title=_(u'monastery')),
                SimpleTerm(value=_(u'S.MTRO'), title=_(u'metro station')),
                SimpleTerm(value=_(u'S.MUS'), title=_(u'museum')),
                SimpleTerm(value=_(u'S.NOV'), title=_(u'novitiate')),
                SimpleTerm(value=_(u'S.NSY'), title=_(u'nursery(-ies)')),
                SimpleTerm(value=_(u'S.OBPT'), title=_(u'observation point')),
                SimpleTerm(value=_(u'S.OBS'), title=_(u'observatory')),
                SimpleTerm(value=_(u'S.OBSR'), title=_(u'radio observatory')),
                SimpleTerm(value=_(u'S.OILJ'), title=_(u'oil pipeline junction')),
                SimpleTerm(value=_(u'S.OILQ'), title=_(u'abandoned oil well')),
                SimpleTerm(value=_(u'S.OILR'), title=_(u'oil refinery')),
                SimpleTerm(value=_(u'S.OILT'), title=_(u'tank farm')),
                SimpleTerm(value=_(u'S.OILW'), title=_(u'oil well')),
                SimpleTerm(value=_(u'S.OPRA'), title=_(u'opera house')),
                SimpleTerm(value=_(u'S.PAL'), title=_(u'palace')),
                SimpleTerm(value=_(u'S.PGDA'), title=_(u'pagoda')),
                SimpleTerm(value=_(u'S.PIER'), title=_(u'pier')),
                SimpleTerm(value=_(u'S.PKLT'), title=_(u'parking lot')),
                SimpleTerm(value=_(u'S.PMPO'), title=_(u'oil pumping station')),
                SimpleTerm(value=_(u'S.PMPW'), title=_(u'water pumping station')),
                SimpleTerm(value=_(u'S.PO'), title=_(u'post office')),
                SimpleTerm(value=_(u'S.PP'), title=_(u'police post')),
                SimpleTerm(value=_(u'S.PPQ'), title=_(u'abandoned police post')),
                SimpleTerm(value=_(u'S.PRKGT'), title=_(u'park gate')),
                SimpleTerm(value=_(u'S.PRKHQ'), title=_(u'park headquarters')),
                SimpleTerm(value=_(u'S.PRN'), title=_(u'prison')),
                SimpleTerm(value=_(u'S.PRNJ'), title=_(u'reformatory')),
                SimpleTerm(value=_(u'S.PRNQ'), title=_(u'abandoned prison')),
                SimpleTerm(value=_(u'S.PS'), title=_(u'power station')),
                SimpleTerm(value=_(u'S.PSH'), title=_(u'hydroelectric power station')),
                SimpleTerm(value=_(u'S.PSN'), title=_(u'nuclear power station')),
                SimpleTerm(value=_(u'S.PSTB'), title=_(u'border post')),
                SimpleTerm(value=_(u'S.PSTC'), title=_(u'customs post')),
                SimpleTerm(value=_(u'S.PSTP'), title=_(u'patrol post')),
                SimpleTerm(value=_(u'S.PYR'), title=_(u'pyramid')),
                SimpleTerm(value=_(u'S.PYRS'), title=_(u'pyramids')),
                SimpleTerm(value=_(u'S.QUAY'), title=_(u'quay')),
                SimpleTerm(value=_(u'S.RDCR'), title=_(u'traffic circle')),
                SimpleTerm(value=_(u'S.RDIN'), title=_(u'intersection')),
                SimpleTerm(value=_(u'S.RECG'), title=_(u'golf course')),
                SimpleTerm(value=_(u'S.RECR'), title=_(u'racetrack')),
                SimpleTerm(value=_(u'S.REST'), title=_(u'restaurant')),
                SimpleTerm(value=_(u'S.RET'), title=_(u'store')),
                SimpleTerm(value=_(u'S.RHSE'), title=_(u'resthouse')),
                SimpleTerm(value=_(u'S.RKRY'), title=_(u'rookery')),
                SimpleTerm(value=_(u'S.RLG'), title=_(u'religious site')),
                SimpleTerm(value=_(u'S.RLGR'), title=_(u'retreat')),
                SimpleTerm(value=_(u'S.RNCH'), title=_(u'ranch(es)')),
                SimpleTerm(value=_(u'S.RSD'), title=_(u'railroad siding')),
                SimpleTerm(value=_(u'S.RSGNL'), title=_(u'railroad signal')),
                SimpleTerm(value=_(u'S.RSRT'), title=_(u'resort')),
                SimpleTerm(value=_(u'S.RSTN'), title=_(u'railroad station')),
                SimpleTerm(value=_(u'S.RSTNQ'), title=_(u'abandoned railroad station')),
                SimpleTerm(value=_(u'S.RSTP'), title=_(u'railroad stop')),
                SimpleTerm(value=_(u'S.RSTPQ'), title=_(u'abandoned railroad stop')),
                SimpleTerm(value=_(u'S.RUIN'), title=_(u'ruin(s)')),
                SimpleTerm(value=_(u'S.SCH'), title=_(u'school')),
                SimpleTerm(value=_(u'S.SCHA'), title=_(u'agricultural school')),
                SimpleTerm(value=_(u'S.SCHC'), title=_(u'college')),
                SimpleTerm(value=_(u'S.SCHL'), title=_(u'language school')),
                SimpleTerm(value=_(u'S.SCHM'), title=_(u'military school')),
                SimpleTerm(value=_(u'S.SCHN'), title=_(u'maritime school')),
                SimpleTerm(value=_(u'S.SCHT'), title=_(u'technical school')),
                SimpleTerm(value=_(u'S.SECP'), title=_(u'State Exam Prep Centre')),
                SimpleTerm(value=_(u'S.SHPF'), title=_(u'sheepfold')),
                SimpleTerm(value=_(u'S.SHRN'), title=_(u'shrine')),
                SimpleTerm(value=_(u'S.SHSE'), title=_(u'storehouse')),
                SimpleTerm(value=_(u'S.SLCE'), title=_(u'sluice')),
                SimpleTerm(value=_(u'S.SNTR'), title=_(u'sanatorium')),
                SimpleTerm(value=_(u'S.SPA'), title=_(u'spa')),
                SimpleTerm(value=_(u'S.SPLY'), title=_(u'spillway')),
                SimpleTerm(value=_(u'S.SQR'), title=_(u'square')),
                SimpleTerm(value=_(u'S.STBL'), title=_(u'stable')),
                SimpleTerm(value=_(u'S.STDM'), title=_(u'stadium')),
                SimpleTerm(value=_(u'S.STNB'), title=_(u'scientific research base')),
                SimpleTerm(value=_(u'S.STNC'), title=_(u'coast guard station')),
                SimpleTerm(value=_(u'S.STNE'), title=_(u'experiment station')),
                SimpleTerm(value=_(u'S.STNF'), title=_(u'forest station')),
                SimpleTerm(value=_(u'S.STNI'), title=_(u'inspection station')),
                SimpleTerm(value=_(u'S.STNM'), title=_(u'meteorological station')),
                SimpleTerm(value=_(u'S.STNR'), title=_(u'radio station')),
                SimpleTerm(value=_(u'S.STNS'), title=_(u'satellite station')),
                SimpleTerm(value=_(u'S.STNW'), title=_(u'whaling station')),
                SimpleTerm(value=_(u'S.STPS'), title=_(u'steps')),
                SimpleTerm(value=_(u'S.SWT'), title=_(u'sewage treatment plant')),
                SimpleTerm(value=_(u'S.SYG'), title=_(u'synagogue')),
                SimpleTerm(value=_(u'S.THTR'), title=_(u'theater')),
                SimpleTerm(value=_(u'S.TMB'), title=_(u'tomb(s)')),
                SimpleTerm(value=_(u'S.TMPL'), title=_(u'temple(s)')),
                SimpleTerm(value=_(u'S.TNKD'), title=_(u'cattle dipping tank')),
                SimpleTerm(value=_(u'S.TOLL'), title=_(u'toll gate/barrier')),
                SimpleTerm(value=_(u'S.TOWR'), title=_(u'tower')),
                SimpleTerm(value=_(u'S.TRAM'), title=_(u'tram')),
                SimpleTerm(value=_(u'S.TRANT'), title=_(u'transit terminal')),
                SimpleTerm(value=_(u'S.TRIG'), title=_(u'triangulation station')),
                SimpleTerm(value=_(u'S.TRMO'), title=_(u'oil pipeline terminal')),
                SimpleTerm(value=_(u'S.TWO'), title=_(u'temp work office')),
                SimpleTerm(value=_(u'S.UNIP'), title=_(u'university prep school')),
                SimpleTerm(value=_(u'S.UNIV'), title=_(u'university')),
                SimpleTerm(value=_(u'S.USGE'), title=_(u'united states government establishment')),
                SimpleTerm(value=_(u'S.VETF'), title=_(u'veterinary facility')),
                SimpleTerm(value=_(u'S.WALL'), title=_(u'wall')),
                SimpleTerm(value=_(u'S.WALLA'), title=_(u'ancient wall')),
                SimpleTerm(value=_(u'S.WEIR'), title=_(u'weir(s)')),
                SimpleTerm(value=_(u'S.WHRF'), title=_(u'wharf(-ves)')),
                SimpleTerm(value=_(u'S.WRCK'), title=_(u'wreck')),
                SimpleTerm(value=_(u'S.WTRW'), title=_(u'waterworks')),
                SimpleTerm(value=_(u'S.ZNF'), title=_(u'free trade zone')),
                SimpleTerm(value=_(u'S.ZOO'), title=_(u'zoo')),
                SimpleTerm(value=_(u'T.ASPH'), title=_(u'asphalt lake')),
                SimpleTerm(value=_(u'T.ATOL'), title=_(u'atoll(s)')),
                SimpleTerm(value=_(u'T.BAR'), title=_(u'bar')),
                SimpleTerm(value=_(u'T.BCH'), title=_(u'beach')),
                SimpleTerm(value=_(u'T.BCHS'), title=_(u'beaches')),
                SimpleTerm(value=_(u'T.BDLD'), title=_(u'badlands')),
                SimpleTerm(value=_(u'T.BLDR'), title=_(u'boulder field')),
                SimpleTerm(value=_(u'T.BLHL'), title=_(u'blowhole(s)')),
                SimpleTerm(value=_(u'T.BLOW'), title=_(u'blowout(s)')),
                SimpleTerm(value=_(u'T.BNCH'), title=_(u'bench')),
                SimpleTerm(value=_(u'T.BUTE'), title=_(u'butte(s)')),
                SimpleTerm(value=_(u'T.CAPE'), title=_(u'cape')),
                SimpleTerm(value=_(u'T.CFT'), title=_(u'cleft(s)')),
                SimpleTerm(value=_(u'T.CLDA'), title=_(u'caldera')),
                SimpleTerm(value=_(u'T.CLF'), title=_(u'cliff(s)')),
                SimpleTerm(value=_(u'T.CNYN'), title=_(u'canyon')),
                SimpleTerm(value=_(u'T.CONE'), title=_(u'cone(s)')),
                SimpleTerm(value=_(u'T.CRDR'), title=_(u'corridor')),
                SimpleTerm(value=_(u'T.CRQ'), title=_(u'cirque')),
                SimpleTerm(value=_(u'T.CRQS'), title=_(u'cirques')),
                SimpleTerm(value=_(u'T.CRTR'), title=_(u'crater(s)')),
                SimpleTerm(value=_(u'T.CUET'), title=_(u'cuesta(s)')),
                SimpleTerm(value=_(u'T.DLTA'), title=_(u'delta')),
                SimpleTerm(value=_(u'T.DPR'), title=_(u'depression(s)')),
                SimpleTerm(value=_(u'T.DSRT'), title=_(u'desert')),
                SimpleTerm(value=_(u'T.DUNE'), title=_(u'dune(s)')),
                SimpleTerm(value=_(u'T.DVD'), title=_(u'divide')),
                SimpleTerm(value=_(u'T.ERG'), title=_(u'sandy desert')),
                SimpleTerm(value=_(u'T.FAN'), title=_(u'fan(s)')),
                SimpleTerm(value=_(u'T.FORD'), title=_(u'ford')),
                SimpleTerm(value=_(u'T.FSR'), title=_(u'fissure')),
                SimpleTerm(value=_(u'T.GAP'), title=_(u'gap')),
                SimpleTerm(value=_(u'T.GRGE'), title=_(u'gorge(s)')),
                SimpleTerm(value=_(u'T.HDLD'), title=_(u'headland')),
                SimpleTerm(value=_(u'T.HLL'), title=_(u'hill')),
                SimpleTerm(value=_(u'T.HLLS'), title=_(u'hills')),
                SimpleTerm(value=_(u'T.HMCK'), title=_(u'hammock(s)')),
                SimpleTerm(value=_(u'T.HMDA'), title=_(u'rock desert')),
                SimpleTerm(value=_(u'T.INTF'), title=_(u'interfluve')),
                SimpleTerm(value=_(u'T.ISL'), title=_(u'island')),
                SimpleTerm(value=_(u'T.ISLET'), title=_(u'islet')),
                SimpleTerm(value=_(u'T.ISLF'), title=_(u'artificial island')),
                SimpleTerm(value=_(u'T.ISLM'), title=_(u'mangrove island')),
                SimpleTerm(value=_(u'T.ISLS'), title=_(u'islands')),
                SimpleTerm(value=_(u'T.ISLT'), title=_(u'land-tied island')),
                SimpleTerm(value=_(u'T.ISLX'), title=_(u'section of island')),
                SimpleTerm(value=_(u'T.ISTH'), title=_(u'isthmus')),
                SimpleTerm(value=_(u'T.KRST'), title=_(u'karst area')),
                SimpleTerm(value=_(u'T.LAVA'), title=_(u'lava area')),
                SimpleTerm(value=_(u'T.LEV'), title=_(u'levee')),
                SimpleTerm(value=_(u'T.MESA'), title=_(u'mesa(s)')),
                SimpleTerm(value=_(u'T.MND'), title=_(u'mound(s)')),
                SimpleTerm(value=_(u'T.MRN'), title=_(u'moraine')),
                SimpleTerm(value=_(u'T.MT'), title=_(u'mountain')),
                SimpleTerm(value=_(u'T.MTS'), title=_(u'mountains')),
                SimpleTerm(value=_(u'T.NKM'), title=_(u'meander neck')),
                SimpleTerm(value=_(u'T.NTK'), title=_(u'nunatak')),
                SimpleTerm(value=_(u'T.NTKS'), title=_(u'nunataks')),
                SimpleTerm(value=_(u'T.PAN'), title=_(u'pan')),
                SimpleTerm(value=_(u'T.PANS'), title=_(u'pans')),
                SimpleTerm(value=_(u'T.PASS'), title=_(u'pass')),
                SimpleTerm(value=_(u'T.PEN'), title=_(u'peninsula')),
                SimpleTerm(value=_(u'T.PENX'), title=_(u'section of peninsula')),
                SimpleTerm(value=_(u'T.PK'), title=_(u'peak')),
                SimpleTerm(value=_(u'T.PKS'), title=_(u'peaks')),
                SimpleTerm(value=_(u'T.PLAT'), title=_(u'plateau')),
                SimpleTerm(value=_(u'T.PLATX'), title=_(u'section of plateau')),
                SimpleTerm(value=_(u'T.PLDR'), title=_(u'polder')),
                SimpleTerm(value=_(u'T.PLN'), title=_(u'plain(s)')),
                SimpleTerm(value=_(u'T.PLNX'), title=_(u'section of plain')),
                SimpleTerm(value=_(u'T.PROM'), title=_(u'promontory(-ies)')),
                SimpleTerm(value=_(u'T.PT'), title=_(u'point')),
                SimpleTerm(value=_(u'T.PTS'), title=_(u'points')),
                SimpleTerm(value=_(u'T.RDGB'), title=_(u'beach ridge')),
                SimpleTerm(value=_(u'T.RDGE'), title=_(u'ridge(s)')),
                SimpleTerm(value=_(u'T.REG'), title=_(u'stony desert')),
                SimpleTerm(value=_(u'T.RK'), title=_(u'rock')),
                SimpleTerm(value=_(u'T.RKFL'), title=_(u'rockfall')),
                SimpleTerm(value=_(u'T.RKS'), title=_(u'rocks')),
                SimpleTerm(value=_(u'T.SAND'), title=_(u'sand area')),
                SimpleTerm(value=_(u'T.SBED'), title=_(u'dry stream bed')),
                SimpleTerm(value=_(u'T.SCRP'), title=_(u'escarpment')),
                SimpleTerm(value=_(u'T.SDL'), title=_(u'saddle')),
                SimpleTerm(value=_(u'T.SHOR'), title=_(u'shore')),
                SimpleTerm(value=_(u'T.SINK'), title=_(u'sinkhole')),
                SimpleTerm(value=_(u'T.SLID'), title=_(u'slide')),
                SimpleTerm(value=_(u'T.SLP'), title=_(u'slope(s)')),
                SimpleTerm(value=_(u'T.SPIT'), title=_(u'spit')),
                SimpleTerm(value=_(u'T.SPUR'), title=_(u'spur(s)')),
                SimpleTerm(value=_(u'T.TAL'), title=_(u'talus slope')),
                SimpleTerm(value=_(u'T.TRGD'), title=_(u'interdune trough(s)')),
                SimpleTerm(value=_(u'T.TRR'), title=_(u'terrace')),
                SimpleTerm(value=_(u'T.UPLD'), title=_(u'upland')),
                SimpleTerm(value=_(u'T.VAL'), title=_(u'valley')),
                SimpleTerm(value=_(u'T.VALG'), title=_(u'hanging valley')),
                SimpleTerm(value=_(u'T.VALS'), title=_(u'valleys')),
                SimpleTerm(value=_(u'T.VALX'), title=_(u'section of valley')),
                SimpleTerm(value=_(u'T.VLC'), title=_(u'volcano')),
                SimpleTerm(value=_(u'U.APNU'), title=_(u'apron')),
                SimpleTerm(value=_(u'U.ARCU'), title=_(u'arch')),
                SimpleTerm(value=_(u'U.ARRU'), title=_(u'arrugado')),
                SimpleTerm(value=_(u'U.BDLU'), title=_(u'borderland')),
                SimpleTerm(value=_(u'U.BKSU'), title=_(u'banks')),
                SimpleTerm(value=_(u'U.BNKU'), title=_(u'bank')),
                SimpleTerm(value=_(u'U.BSNU'), title=_(u'basin')),
                SimpleTerm(value=_(u'U.CDAU'), title=_(u'cordillera')),
                SimpleTerm(value=_(u'U.CNSU'), title=_(u'canyons')),
                SimpleTerm(value=_(u'U.CNYU'), title=_(u'canyon')),
                SimpleTerm(value=_(u'U.CRSU'), title=_(u'continental rise')),
                SimpleTerm(value=_(u'U.DEPU'), title=_(u'deep')),
                SimpleTerm(value=_(u'U.EDGU'), title=_(u'shelf edge')),
                SimpleTerm(value=_(u'U.ESCU'), title=_(u'escarpment (or scarp)')),
                SimpleTerm(value=_(u'U.FANU'), title=_(u'fan')),
                SimpleTerm(value=_(u'U.FLTU'), title=_(u'flat')),
                SimpleTerm(value=_(u'U.FRZU'), title=_(u'fracture zone')),
                SimpleTerm(value=_(u'U.FURU'), title=_(u'furrow')),
                SimpleTerm(value=_(u'U.GAPU'), title=_(u'gap')),
                SimpleTerm(value=_(u'U.GLYU'), title=_(u'gully')),
                SimpleTerm(value=_(u'U.HLLU'), title=_(u'hill')),
                SimpleTerm(value=_(u'U.HLSU'), title=_(u'hills')),
                SimpleTerm(value=_(u'U.HOLU'), title=_(u'hole')),
                SimpleTerm(value=_(u'U.KNLU'), title=_(u'knoll')),
                SimpleTerm(value=_(u'U.KNSU'), title=_(u'knolls')),
                SimpleTerm(value=_(u'U.LDGU'), title=_(u'ledge')),
                SimpleTerm(value=_(u'U.LEVU'), title=_(u'levee')),
                SimpleTerm(value=_(u'U.MESU'), title=_(u'mesa')),
                SimpleTerm(value=_(u'U.MNDU'), title=_(u'mound')),
                SimpleTerm(value=_(u'U.MOTU'), title=_(u'moat')),
                SimpleTerm(value=_(u'U.MTU'), title=_(u'mountain')),
                SimpleTerm(value=_(u'U.PKSU'), title=_(u'peaks')),
                SimpleTerm(value=_(u'U.PKU'), title=_(u'peak')),
                SimpleTerm(value=_(u'U.PLNU'), title=_(u'plain')),
                SimpleTerm(value=_(u'U.PLTU'), title=_(u'plateau')),
                SimpleTerm(value=_(u'U.PNLU'), title=_(u'pinnacle')),
                SimpleTerm(value=_(u'U.PRVU'), title=_(u'province')),
                SimpleTerm(value=_(u'U.RDGU'), title=_(u'ridge')),
                SimpleTerm(value=_(u'U.RDSU'), title=_(u'ridges')),
                SimpleTerm(value=_(u'U.RFSU'), title=_(u'reefs')),
                SimpleTerm(value=_(u'U.RFU'), title=_(u'reef')),
                SimpleTerm(value=_(u'U.RISU'), title=_(u'rise')),
                SimpleTerm(value=_(u'U.SCNU'), title=_(u'seachannel')),
                SimpleTerm(value=_(u'U.SCSU'), title=_(u'seachannels')),
                SimpleTerm(value=_(u'U.SDLU'), title=_(u'saddle')),
                SimpleTerm(value=_(u'U.SHFU'), title=_(u'shelf')),
                SimpleTerm(value=_(u'U.SHLU'), title=_(u'shoal')),
                SimpleTerm(value=_(u'U.SHSU'), title=_(u'shoals')),
                SimpleTerm(value=_(u'U.SHVU'), title=_(u'shelf valley')),
                SimpleTerm(value=_(u'U.SILU'), title=_(u'sill')),
                SimpleTerm(value=_(u'U.SLPU'), title=_(u'slope')),
                SimpleTerm(value=_(u'U.SMSU'), title=_(u'seamounts')),
                SimpleTerm(value=_(u'U.SMU'), title=_(u'seamount')),
                SimpleTerm(value=_(u'U.SPRU'), title=_(u'spur')),
                SimpleTerm(value=_(u'U.TERU'), title=_(u'terrace')),
                SimpleTerm(value=_(u'U.TMSU'), title=_(u'tablemounts (or guyots)')),
                SimpleTerm(value=_(u'U.TMTU'), title=_(u'tablemount (or guyot)')),
                SimpleTerm(value=_(u'U.TNGU'), title=_(u'tongue')),
                SimpleTerm(value=_(u'U.TRGU'), title=_(u'trough')),
                SimpleTerm(value=_(u'U.TRNU'), title=_(u'trench')),
                SimpleTerm(value=_(u'U.VALU'), title=_(u'valley')),
                SimpleTerm(value=_(u'U.VLSU'), title=_(u'valleys')),
                SimpleTerm(value=_(u'V.BUSH'), title=_(u'bush(es)')),
                SimpleTerm(value=_(u'V.CULT'), title=_(u'cultivated area')),
                SimpleTerm(value=_(u'V.FRST'), title=_(u'forest(s)')),
                SimpleTerm(value=_(u'V.FRSTF'), title=_(u'fossilized forest')),
                SimpleTerm(value=_(u'V.GROVE'), title=_(u'grove')),
                SimpleTerm(value=_(u'V.GRSLD'), title=_(u'grassland')),
                SimpleTerm(value=_(u'V.GRVC'), title=_(u'coconut grove')),
                SimpleTerm(value=_(u'V.GRVO'), title=_(u'olive grove')),
                SimpleTerm(value=_(u'V.GRVP'), title=_(u'palm grove')),
                SimpleTerm(value=_(u'V.GRVPN'), title=_(u'pine grove')),
                SimpleTerm(value=_(u'V.HTH'), title=_(u'heath')),
                SimpleTerm(value=_(u'V.MDW'), title=_(u'meadow')),
                SimpleTerm(value=_(u'V.OCH'), title=_(u'orchard(s)')),
                SimpleTerm(value=_(u'V.SCRB'), title=_(u'scrubland')),
                SimpleTerm(value=_(u'V.TREE'), title=_(u'tree(s)')),
                SimpleTerm(value=_(u'V.TUND'), title=_(u'tundra')),
                SimpleTerm(value=_(u'V.VIN'), title=_(u'vineyard')),
                SimpleTerm(value=_(u'V.VINS'), title=_(u'vineyards')),
                SimpleTerm(value=_(u'null'), title=_(u'not available')),
            ]
        )

        return geoname_featurecodes

GeonameFeaturecodesVocabFactory = GeonameFeaturecodesVocab()
